#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES XD (SERVER DEVELOPMENT)" \
       --checklist "Please select the packages you wish to install \
from series XD. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. \
Press ENTER when you are \
done." 14 70 4 \
"xf_kit1" "XFree86 3.1 Linkkit" "off" \
"xf_kit2" "XFree86 3.1 Linkkit" "off" \
"xf_pex" "XFree86 3.1 PEX distribution" "off" \
"xstatic" "Static versions of the X libs" "off" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in xf_kit1 xf_kit2 xf_pex xstatic ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
