#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES XD (X DEVELOPMENT)" \
       --checklist "Please select the packages you wish to install \
from series XD. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. Recommended packages have \
already been selected for you, but you may unselect them if you wish. \
You must install xf_prog in order to compile anything for X. \
Press ENTER when you are \
done." 18 70 6 \
"xf_kit" "XFree86 2.0 Linkkit (server builder)" "off" \
"xman3" "Man pages for the X11 programming libraries" "off" \
"xf_prog" "XFree86 2.0 Program Development Kit" "on" \
"xkitlib1" "Libs needed by the XFree86 2.0 Linkkit" "off" \
"xkitlib2" "Libs needed by the XFree86 2.0 Linkkit" "off" \
"xf_pex" "XFree86 2.0 PEX libraries" "off" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in xkitlib2 xf_pex xf_kit xman3 xf_prog xkitlib1 ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
