.EXPORT_ALL_VARIABLES:

CFLAGS	= -include /usr/include/bsd/bsd.h -I/usr/include/bsd \
	-O2 -m486 -fomit-frame-pointer -I../common_source
LDFLAGS	= -N
LDLIBS = -lbsd -lcommon -L ../common_source


SUBDIRS	= common_source filters lpc lpd lpq lpr lprm lptest pac

all:
	for i in $(SUBDIRS); do make -C $$i all; done

install:
	for i in $(SUBDIRS); do make -C $$i install; done

clean:
	for i in $(SUBDIRS); do make -C $$i clean; done
