#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES Q (ALPHA KERNEL IMAGES/SOURCE)" \
       --checklist "Please select the packages you wish to install \
from series Q. Use the UP/DOWN keys to scroll through the list, and the SPACE \
key to select the packages you wish to install. Select a maximum of one kernel \
image, and make sure to reinstall LILO before rebooting (if you use it). \
Press ENTER when you are done. NOTE: All of the kernels here support UMSDOS. \
For an exact listing of the drivers included with each image, see the logfiles \
on each disk. (idekern.log, scsikern.log, etc.)" \
20 70 6 \
"v1_1_16" "Linux kernel source v.1.1.16" "on" \
"i1_1_16" "Kernel include files for v.1.1.16" "on" \
"ifs" "patches/utilities for IFS 5.1 for 1.1.x" "off" \
"ftape16" "Floppy tape modules for the 1.1.16 kernel" "off" \
"idekern" "Kernel v. 1.1.16 with IDE support" "off" \
"scsikern" "Kernel v. 1.1.16 with IDE+SCSI support" "off" \
"mitsumi" "Kernel v. 1.1.16 with IDE+SCSI+Mitsumi CD" "off" \
"mitsumi2" "Kernel v. 1.1.16 with fast Mitsumi driver" "off" \
"cdu31a" "Kernel v. 1.1.16 with IDE+SCSI+Sony CDU31A" "off" \
"sony535" "Kernel v. 1.1.16 with IDE+SCSI+Sony535" "off" \
"sbpcd" "Kernel v. 1.1.16 with IDE+SCSI+SB Pro CD" "off" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in v1_1_16 i1_1_16 ifs idekern scsikern mitsumi cdu31a \
mitsumi2 sony535 sbpcd ftape16 ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
