#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES AP (APPLICATIONS)" \
       --checklist "Please select the packages you wish to install \
from series AP. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. Recommended packages have \
already been selected for you, but you may unselect them if you wish. \
Press ENTER when you are \
done." 22 70 11 \
"english" "The International version of ispell (3.009)" "off" \
"ispell" "GNU ispell 4.0 (interactive spell checker)" "off" \
"jove" "Jonathan's Own Version of Emacs text editor" "off" \
"man" "On-line manual pages" "on" \
"manpgs" "More man pages" "on" \
"diff" "GNU diffutils" "on" \
"sudo" "Allow special users limited root access" "off" \
"termbin" "The executable files for term" "off" \
"termnet" "ttelnet, tfinger, and tncftp for term" "off" \
"termsrc" "SOURCE code for term" "off" \
"ghostscr" "GNU Ghostscript version 2.6.1" "off" \
"gsfonts1" "Fonts for the Postscript interpreter" "off" \
"gsfonts2" "More fonts for the Postscript interpreter" "off" \
"jed" "JED programmer's editor" "on" \
"joe" "joe text editor, version 1.0.8" "on" \
"bc" "GNU bc - arbitrary precision math language" "off" \
"workbone" "Workbone 0.1 text-based audio CD player" "off" \
"ftape" "floppy controller tape drive support" "off" \
"mt_st" "mt ported from BSD - controls tape drive" "off" \
"gonzo" "Sample users gonzo, snake, and satan" "off" \
"gp9600" "Changes the default modem speed" "off" \
"groff" "GNU troff 1.09 document formatting system" "off" \
"quota" "quota-1.33 for Linux 1.1.21+" "off" \
"sc" "The 'sc' spreadsheet" "off" \
"texinfo" "GNU texinfo documentation system" "on" \
"vim" "Improved vi clone" "off" \
"ash" "A small /bin/sh type shell - 62K" "off" \
"zsh" "Zsh - a custom *nix shell" "off" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in english ispell jove man manpgs termbin termsrc bc gonzo \
gp9600 groff quota sc workbone ghostscr gsfonts1 joe gsfonts2 ftape \
termnet ash jed mt_st texinfo vim sudo diff zsh ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
