#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES IV (InterViews 3.1)" \
       --checklist "Please select the package you wish to install \
from series IV. Required packages are selected already, but you \
may select any combination of packages you like. \
Press ENTER when you are \
done." 13 70 3 \
"libiv_so" "Shared IV libraries" "on" \
"iv_bin" "InterViews binaries (including doc and idraw)" "on" \
"iv_docs" "Manual pages and other documentation" "off" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in libiv_so iv_bin iv_docs ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
