#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES OOP (GNU Smalltalk)" \
       --checklist "Please select the packages you wish to install \
from series OOP. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. \
Press ENTER when you are \
done." 12 70 2 \
"smaltalk" "GNU Smalltalk 1.1.1" "on" \
"stix" "A Smalltalk interface to X11" "off" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in smaltalk stix ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
