#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES X (XFree86 2.1.1)" \
       --checklist "Please select the packages you wish to install \
from series X. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. Recommended packages have \
already been selected for you, but you may unselect them if you wish. \
Make sure you install an X11 server for your video card. These are the \
top 7 choices. \
Press ENTER when you are \
done." 22 70 9 \
"x_8514" "SERVER for cards using IBM8514 chips" "off" \
"x_mach32" "SERVER for cards using Mach32 chips" "off" \
"x_mach8" "SERVER for cards using Mach8 chips" "off" \
"x_mono" "A Monochrome SERVER" "off" \
"x_s3" "SERVER for cards using S3 chips" "off" \
"x_svga" "A SuperVGA server" "off" \
"x_vga16" "16 color VGA/EGA generic SERVER" "off" \
"xf_doc" "Documentation and release notes for X" "off" \
"config86" "Configures your Xconfig file" "on" \
"xpm" "The Xpm shared library" "on" \
"xf_cfg" "XDM configuration, chooser, and FVWM 1.20" "on" \
"xf_lib" "Libraries, bitmaps and minimal fonts for X" "on" \
"xinclude" "Header files for X programming" "on" \
"xman1" "Man pages for programs that come with X" "on" \
"xf_bin" "Basic client binaries required for X" "on" \
"xfnt" "Basic fonts needed to run X" "on" \
"xfnt75" "75 dpi fonts" "on" \
"fnt100_1" "100 dpi fonts part one" "off" \
"fnt100_2" "100 dpi fonts part two" "off" \
"speedo" "scalable fonts" "off" \
"fntbig1" "Big fonts part one" "off" \
"fntbig2" "Big fonts part two" "off" \
"xlock" "A screensaver/locker for X" "on" \
"xconfig" "A collection of sample Xconfig files" "off" \
"fvwmicns" "Color icons from xpm3icons.tar.Z" "off" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in x_8514 x_mach32 x_mach8 xf_doc xlock fvwmicns xfnt xfnt75 \
xf_bin x_vga16 xconfig xf_lib xman1 xinclude x_mono x_s3 x_svga xpm xf_cfg \
config86 fnt100_1 fnt100_2 speedo fntbig1 fntbig2 ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
