#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES A (BASE LINUX SYSTEM)" \
       --checklist "Please select the packages you wish to install \
from series A. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. Certain important packages have \
already been selected for you, and you are cautioned against unselecting \
these packages. However, it's your system. :^)  Press ENTER when you are \
done." 22 70 10 \
"base" "Basic filesystem, shell, and utils - REQUIRED" "on" \
"bash" "GNU bash-1.14 shell - REQUIRED" "on" \
"devs" "Device files found in /dev - REQUIRED" "on" \
"etc"  "System config files & utilities - REQUIRED" "on" \
"idekern"  "Linux kernel 1.0.9 no SCSI (YOU NEED 1 KERNEL)" "on" \
"scsikern" "Linux kernel 1.0.9 IDE+SCSI (YOU NEED 1 KERNEL)" "on" \
"hdsetup" "Slackware setup scripts - REQUIRED" "on" \
"lilo" "Boots Linux from your hard drive. (v. 0.14)" "on" \
"sysvinit" "System V-like INIT programs - REQUIRED" "on" \
"bin"      "GNU fileutils 3.9, elvis, etc. - REQUIRED" "on" \
"ldso" "dynamic linker/loader - REQUIRED" "on" \
"bootutls" "bootutils filesys check - REQUIRED" "on" \
"getty" "getty_ps 2.0.7e - OPTIONAL" "off" \
"gzip"  "The GNU zip compression - REQUIRED" "on" \
"ps" "displays process info - REQUIRED" "on" \
"shlibs" "The shared C libraries - REQUIRED" "on" \
"util" "util-linux utilities - REQUIRED" "on" \
"comms" "Serial transfer and modem comm packages" "on" \
"cpio" "The GNU cpio backup/archiving utility" "on" \
"e2fsbn" "Utilities for the ext2 file system" "on" \
"find" "GNU find 3.8" "on" \
"grep" "GNU grep 2.0" "on" \
"keytbls" "Change keyboard mappings" "on" \
"lpr" "Print spooling system." "on" \
"select" "Cut and paste text with your mouse" "on" \
"shellutl" "GNU shellutils-1.9 - REQUIRED" "on" \
"shlbsvga" "Shared svga library" "on" \
"syslogd" "logs system and kernel messages" "on" \
"tar" "GNU tar 1.11.2 - REQUIRED" "on" \
"tcsh" "Extended C shell version 6.04" "off" \
"textutl" "GNU textutil-1.9 - REQUIRED" "on" \
"zoneinfo" "Configures your time zone" "on" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in base devs etc idekern scsikern lilo sysvinit bin ldso \
bash bootutls getty gzip ps shlibs util comms cpio e2fsbn find grep keytbls \
lpr select shellutl hdsetup shlbsvga syslogd tar tcsh textutl zoneinfo ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
