#!/bin/sh
dialog --title "GNU GNAT (Ada9x compiler - requires GCC 2.6.0)" \
       --checklist "Please select the packages you would like to install to your hard drive from the Slackware Professional CD-ROM.  The disk must be mounted under /cdrom for this to work. If you are upgrading a package that currently runs from your CD-ROM, you may wish to save any configuration files first. (they will be reset) Press ENTER when you are done." \
14 70 2 \
"gnat_bin" "Binaries for GNU GNAT 1.82" "off" \
"gnat_lib" "Libraries for GNU GNAT 1.82" "off" \
2> /tmp/return
if fgrep '"gnat_bin"' /tmp/return 1> /dev/null 2> /dev/null ; then
 dialog --title "Installing package gnat_bin to your hard drive" --infobox \
"Binaries for GNU GNAT 1.82\n\
\n\
GNu Ada Translator, an Ada83 and Ada9X front end to gcc-2.6.0.  You\n\
will need to install GCC-2.6.0 in order to use this compiler.\n\
\n\
" 7 75
 installpkg gnat_bin.tgz 1> /dev/null 2> /dev/null
fi
if fgrep '"gnat_lib"' /tmp/return 1> /dev/null 2> /dev/null ; then
 dialog --title "Installing package gnat_lib to your hard drive" --infobox \
"Libraries for GNU GNAT 1.82\n\
\n\
Libraries for the GNu Ada Translator, an Ada83 and Ada9X front end to\n\
gcc-2.6.0.  You will need to install GCC-2.6.0 in order to use this\n\
compiler.\n\
\n\
" 8 75
 installpkg gnat_lib.tgz 1> /dev/null 2> /dev/null
fi
rm -f /tmp/return
