#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES TCL (Tcl/Tk,etc.)" \
       --checklist "Please select the packages you wish to install \
from series TCL. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. Recommended packages have \
already been selected for you, but you may unselect them if you wish. \
Press ENTER when you are \
done." 16 70 5 \
"tcl" "The TCL script language" "on" \
"tk" "The TK toolkit for TCL" "on" \
"blt" "The BLT library extension to Tk" "off" \
"itcl" "[incr Tcl] OOP Tcl" "off" \
"tclx" "TclX - Extended Tcl" "on" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in blt itcl tclx tcl tk ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
