#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES NCR (NCR53c810 SCSI)" \
       --checklist "Please select the packages you wish to install \
from series NCR. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. Recommended packages are already selected. \
Press ENTER when you are \
done." 13 70 3 \
"ncr_krn3" "Linux 1.1.19 source with ncr53c810" "off" \
"ncr_inc3" "Linux 1.1.19 include files for ncr_krn3" "on" \
"ncrkern3" "Linux 1.1.19 kernel with ncr53c810" "on" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in ncr_krn3 ncr_inc3 ncrkern3 ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
