all:	pac

pac:	pac.o

install: pac
	install -s -m500 pac /usr/sbin
	install -m644 pac.8 /usr/man/man8

clean:
	rm -f lptest *.o

all:	pac

pac:	pac.o

install: pac
	install -s -m500 pac /usr/sbin
	install -m644 pac.8 /usr/man/man8

clean:
	rm -f lptest *.o

