#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES X (XFree86 3.1)" \
       --checklist "Please select the packages you wish to install \
from series X. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. Recommended packages have \
already been selected for you, but you may unselect them if you wish. \
Make sure you install an X11 server for your video card. These are the \
packages that start with 'x_'. \
Press ENTER when you are \
done." 22 70 9 \
"config86" "Configures your XF86Config file" "on" \
"fnt100_1" "100 dpi fonts, part one" "off" \
"fnt100_2" "100 dpi fonts, part two" "off" \
"fntbig1" "Big fonts, part one" "off" \
"fntbig2" "Big fonts, part two" "off" \
"fntbig3" "Big fonts, part three" "off" \
"fntscl" "Scalable Speedo/Type1 fonts" "off" \
"fvwmicns" "Color icons from xpm3icons.tar.Z" "off" \
"oldlibs" "XFree86 2.1.1 shared libraries" "on" \
"x_8514" "SERVER for cards using IBM8514 chips" "off" \
"x_agx" "SERVER for cards using AGX chips" "off" \
"x_mach32" "SERVER for cards using Mach32 chips" "off" \
"x_mach8" "SERVER for cards using Mach8 chips" "off" \
"x_mono" "A Monochrome SERVER" "off" \
"x_p9000" "A SERVER for cards using P9000 chips" "off" \
"x_s3" "SERVER for cards using S3 chips" "off" \
"x_svga" "SERVER for SuperVGA cards" "off" \
"x_vga16" "A 16-color generic SERVER" "off" \
"x_w32" "SERVER for cards using the ET4000/W32 chipset" "off" \
"xextra" "Two experimental X servers" "off" \
"xf_bin" "Basic client binaries required for X" "on" \
"xf_cfg" "XDM configuration, chooser, and FVWM" "on" \
"xf_ctrb" "Extra programs from X11R6 contrib" "off" \
"xf_doc" "Documentation for XFree86 3.1" "off" \
"xf_lib" "Libraries and bitmaps for X" "on" \
"xfnt" "Basic fonts needed to run X" "on" \
"xfnt75" "75 dpi fonts" "on" \
"xinclude" "Header files for X programming" "on" \
"xlock" "A screensaver/locker for X" "on" \
"xman" "Man pages for XFree86 3.1" "on" \
"xpm" "The Xpm shared library" "on" \
"xusrbin" "Daemon needed for rstart" "off" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in config86 fnt100_1 fnt100_2 fntbig1 fntbig2 fntbig3 fntscl \
fvwmicns oldlibs x_8514 x_agx x_mach32 x_mach8 x_mono x_p9000 x_s3 x_svga \
x_vga16 x_w32 xextra xf_bin xf_cfg xf_ctrb xf_doc xf_lib xfnt xfnt75 xinclude \
xlock xman xpm xusrbin ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
