#!/bin/sh
dialog --title "Install packages from the Y series (Text Games)" \
       --checklist "Please select the packages you would like to install to your hard drive from the Slackware Professional CD-ROM.  Press ENTER when you are done." \
12 70 3 \
"bsdgames" "BSD text games" "off" \
"sastroid" "Sasteroids 1.3" "off" \
"tetris" "Tetris for terminals" "off" \
2> /tmp/return
if fgrep '"bsdgames"' /tmp/return 1> /dev/null 2> /dev/null ; then
 dialog --title "Installing package bsdgames to your hard drive" --infobox \
"Curtis Olson and Andy Tefft's port of the BSD games collection. (1.3)\n\
\n\
This package puts these games into /usr/games:\n\
arithmetic atc backgammon battlestar bcd bog caesar canfield\n\
cfscores cribbage factor fish fortune hangman hunt mille monop\n\
morse number paranoia pom ppt primes rain robots sail snake\n\
snscore teachgammon trek wargames worm worms wump\n\
\n\
Adds a call to 'fortune' to /etc/profile and /etc/csh.login, so that\n\
users will get a fortune message when they log in.\n\
\n\
" 13 75
 installpkg y1/bsdgames.tgz 1> /dev/null 2> /dev/null
fi
if fgrep '"sastroid"' /tmp/return 1> /dev/null 2> /dev/null ; then
 dialog --title "Installing package sastroid to your hard drive" --infobox \
"Sasteroids 1.3\n\
\n\
Sasteroids is an asteroids-like game, the whole point to shoot\n\
asteroids and an occasional enemy space ship.  Ok, so its not DOOM,\n\
but it can be amusing, and does use a few DOOM-like brown colors.\n\
This started out as a direct port of xasteroids to run under svgalib\n\
(a wonderful super-vga graphics library by Harm Hanemaayer)\n\
\n\
Sasteroids was derived from Phil Goetz's Xasteroids by Brad Pitzel.\n\
\n\
" 12 75
 installpkg y1/sastroid.tgz 1> /dev/null 2> /dev/null
fi
if fgrep '"tetris"' /tmp/return 1> /dev/null 2> /dev/null ; then
 dialog --title "Installing package tetris to your hard drive" --infobox \
"Tetris for terminals.\n\
\n\
" 4 75
 installpkg y1/tetris.tgz 1> /dev/null 2> /dev/null
fi
rm -f /tmp/return
