#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES IV (Interviews)" \
       --checklist "Please select the packages you wish to install \
from series IV. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. \
Press ENTER when you are \
done." 14 70 4 \
"ivlibs31" "libraries for programming InterViews" "off" \
"ivincs" "include files for programming InterViews" "off" \
"doc31" "An X based WYSIWYG editor. Saves in TeX format" "off" \
"idraw" " A drawing program that saves in Postscript" "off" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in elisp2 emac_nox elisp1 elispc emacmisc emacsbin ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
